// <auto-generated />
using System;
using AvitoPRService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvitoPRService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvitoPRService.Domain.Entities.PullRequest", b =>
                {
                    b.Property<string>("PullRequestId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<string>("PullRequestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pull_request_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("PullRequestId");

                    b.HasIndex("AuthorId");

                    b.ToTable("pull_request", (string)null);
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.Reviewer", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("PullRequestId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pull_request_id");

                    b.HasKey("UserId", "PullRequestId");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("idx_reviewer_pr");

                    b.ToTable("reviewer", (string)null);
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.HasKey("TeamName");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("TeamName");

                    b.HasIndex("Username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.PullRequest", b =>
                {
                    b.HasOne("AvitoPRService.Domain.Entities.User", "Author")
                        .WithMany("PullRequests")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.Reviewer", b =>
                {
                    b.HasOne("AvitoPRService.Domain.Entities.PullRequest", "PullRequest")
                        .WithMany("Reviewers")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvitoPRService.Domain.Entities.User", "User")
                        .WithMany("Reviewers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PullRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.User", b =>
                {
                    b.HasOne("AvitoPRService.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.PullRequest", b =>
                {
                    b.Navigation("Reviewers");
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AvitoPRService.Domain.Entities.User", b =>
                {
                    b.Navigation("PullRequests");

                    b.Navigation("Reviewers");
                });
#pragma warning restore 612, 618
        }
    }
}
