//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace AvitoPRService.Api
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IController
    {

        /// <summary>
        /// Создать команду с участниками (создаёт/обновляет пользователей)
        /// </summary>


        /// <returns>Команда создана</returns>

        System.Threading.Tasks.Task<CreateTeamResponse> AddAsync(TeamDto body);

        /// <summary>
        /// Получить команду с участниками
        /// </summary>

        /// <param name="team_name">Уникальное имя команды</param>

        /// <returns>Объект команды</returns>

        System.Threading.Tasks.Task<TeamDto> GetAsync(string team_name);

        /// <summary>
        /// Установить флаг активности пользователя
        /// </summary>


        /// <returns>Обновлённый пользователь</returns>

        System.Threading.Tasks.Task<SetUserIsActiveResponse> SetIsActiveAsync(SetUserIsActiveRequest setUserIsActiveRequest);

        /// <summary>
        /// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
        /// </summary>


        /// <returns>PR создан</returns>

        System.Threading.Tasks.Task<CreatePullRequestResponse> CreateAsync(CreatePullRequestRequest body);

        /// <summary>
        /// Пометить PR как MERGED (идемпотентная операция)
        /// </summary>


        /// <returns>PR в состоянии MERGED</returns>

        System.Threading.Tasks.Task<MergePullRequestResponse> MergeAsync(MergePullRequestRequest body);

        /// <summary>
        /// Переназначить конкретного ревьювера на другого из его команды
        /// </summary>


        /// <returns>Переназначение выполнено</returns>

        System.Threading.Tasks.Task<ReassignReviewerResponse> ReassignAsync(ReassingReviewerRequest body);

        /// <summary>
        /// Получить PR'ы, где пользователь назначен ревьювером
        /// </summary>

        /// <param name="user_id">Идентификатор пользователя</param>

        /// <returns>Список PR'ов пользователя</returns>

        System.Threading.Tasks.Task<GetReviewResponse> GetReviewAsync(string user_id);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public partial class Controller : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IController _implementation;

        public Controller(IController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Создать команду с участниками (создаёт/обновляет пользователей)
        /// </summary>
        /// <returns>Команда создана</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("team/add")]
        public System.Threading.Tasks.Task<CreateTeamResponse> Add([Microsoft.AspNetCore.Mvc.FromBody] TeamDto body)
        {

            return _implementation.AddAsync(body);
        }

        /// <summary>
        /// Получить команду с участниками
        /// </summary>
        /// <param name="team_name">Уникальное имя команды</param>
        /// <returns>Объект команды</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("team/get")]
        public System.Threading.Tasks.Task<TeamDto> Get([Microsoft.AspNetCore.Mvc.FromQuery] string team_name)
        {

            return _implementation.GetAsync(team_name);
        }

        /// <summary>
        /// Установить флаг активности пользователя
        /// </summary>
        /// <returns>Обновлённый пользователь</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("users/setIsActive")]
        public System.Threading.Tasks.Task<SetUserIsActiveResponse> SetIsActive([Microsoft.AspNetCore.Mvc.FromBody] SetUserIsActiveRequest setUserIsActiveRequest)
        {

            return _implementation.SetIsActiveAsync(setUserIsActiveRequest);
        }

        /// <summary>
        /// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
        /// </summary>
        /// <returns>PR создан</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("pullRequest/create")]
        public System.Threading.Tasks.Task<CreatePullRequestResponse> Create([Microsoft.AspNetCore.Mvc.FromBody] CreatePullRequestRequest body)
        {

            return _implementation.CreateAsync(body);
        }

        /// <summary>
        /// Пометить PR как MERGED (идемпотентная операция)
        /// </summary>
        /// <returns>PR в состоянии MERGED</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("pullRequest/merge")]
        public System.Threading.Tasks.Task<MergePullRequestResponse> Merge([Microsoft.AspNetCore.Mvc.FromBody] MergePullRequestRequest body)
        {

            return _implementation.MergeAsync(body);
        }

        /// <summary>
        /// Переназначить конкретного ревьювера на другого из его команды
        /// </summary>
        /// <returns>Переназначение выполнено</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("pullRequest/reassign")]
        public System.Threading.Tasks.Task<ReassignReviewerResponse> Reassign([Microsoft.AspNetCore.Mvc.FromBody] ReassingReviewerRequest body)
        {

            return _implementation.ReassignAsync(body);
        }

        /// <summary>
        /// Получить PR'ы, где пользователь назначен ревьювером
        /// </summary>
        /// <param name="user_id">Идентификатор пользователя</param>
        /// <returns>Список PR'ов пользователя</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("users/getReview")]
        public System.Threading.Tasks.Task<GetReviewResponse> GetReview([Microsoft.AspNetCore.Mvc.FromQuery] string user_id)
        {

            return _implementation.GetReviewAsync(user_id);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PullRequestStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"OPEN")]
        OPEN = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"MERGED")]
        MERGED = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PullRequestShortStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"OPEN")]
        OPEN = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"MERGED")]
        MERGED = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ErrorCode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"TEAM_EXISTS")]
        TEAM_EXISTS = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"PR_EXISTS")]
        PR_EXISTS = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"PR_MERGED")]
        PR_MERGED = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"NOT_ASSIGNED")]
        NOT_ASSIGNED = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"NO_CANDIDATE")]
        NO_CANDIDATE = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"NOT_FOUND")]
        NOT_FOUND = 5,

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765